# Generated by Django 3.1.4 on 2020-12-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=15, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_num',
            field=models.IntegerField(verbose_name='우편번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_addr',
            field=models.CharField(max_length=15, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=15, verbose_name='이름'),
        ),
    ]
