# Generated by Django 3.1.4 on 2020-12-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_date',
        ),
    ]
