# Generated by Django 3.1.4 on 2021-01-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('4canceled', 'status_canceled'), ('5completed', 'status_completed'), ('3rejected', 'status_rejected'), ('1proposed', 'status_proposed'), ('2progress', 'status_progress')], default='1proposed', max_length=12),
        ),
    ]
