# Generated by Django 3.1.4 on 2021-01-12 14:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20210104_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('5completed', 'status_completed'), ('2progress', 'status_progress'), ('3rejected', 'status_rejected'), ('1proposed', 'status_proposed'), ('4canceled', 'status_canceled')], default='1proposed', max_length=12),
        ),
    ]
