# Generated by Django 3.1.4 on 2021-01-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=50, verbose_name='수신자')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='참조')),
                ('reference_hide', models.CharField(blank=True, max_length=200, null=True, verbose_name='숨은 참조')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('mail_options', models.CharField(choices=[('default', 'Default'), ('appr', 'Appr')], default='default', max_length=50)),
                ('upload_files', models.FileField(blank=True, null=True, upload_to='mail', verbose_name='파일')),
                ('filename', models.CharField(blank=True, max_length=64, null=True, verbose_name='첨부파일명')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
