# Generated by Django 3.1.4 on 2020-12-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='appr_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appr_mail', to='users.user', verbose_name='승인자'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='contents',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='filename',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='참조'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='reference_hide',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='숨은 참조'),
        ),
    ]
