# Generated by Django 3.1.4 on 2020-12-20 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='board',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='board',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='board',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='users.user', verbose_name='작성자'),
        ),
    ]
