# Generated by Django 3.1.4 on 2020-12-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201220_1720'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_num',
        ),
        migrations.RemoveField(
            model_name='board',
            name='view_cnts',
        ),
        migrations.AddField(
            model_name='board',
            name='postNo',
            field=models.CharField(blank=True, max_length=8, verbose_name='게시물 번호'),
        ),
        migrations.AddField(
            model_name='board',
            name='viewCnts',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='users.user', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='제목'),
        ),
    ]
