# Generated by Django 3.1.4 on 2020-12-29 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_go_work', models.DateTimeField(default=django.utils.timezone.now, verbose_name='출근시간')),
                ('time_leave_work', models.DateTimeField(verbose_name='퇴근시간')),
            ],
        ),
    ]
