# Generated by Django 3.1.4 on 2021-01-04 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_go_work', models.DateTimeField(default=django.utils.timezone.now, verbose_name='출근시간')),
                ('time_leave_work', models.DateTimeField(verbose_name='퇴근시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='직원이름')),
            ],
        ),
    ]
